# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'octo99/weatherapi'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 
          $(tag)

- stage: Provision
  displayName: Terraforming on Azure
  dependsOn: Build
  jobs:  
  - job: Provision
    displayName: Provisioning Container Instance
    pool:
      vmImage: 'ubuntu-latest'
    variables:
    - group: TerraformSPvars
    steps:
    - script: 
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        TF_VAR_imagebuild: $(tag)
    - task: TerraformCLI@0
      inputs:
        command: 'init'
        allowTelemetryCollection: true
    - task: TerraformCLI@0
      inputs:
        command: 'validate'
        allowTelemetryCollection: true
    
    - task: TerraformCLI@0
      inputs:
        command: 'plan'
        allowTelemetryCollection: true
